/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\资料手册\\博客VuePress\\docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-58714c4c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58714c4c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-221222d8",
    path: "/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-221222d8").then(next)
    },
  },
  {
    name: "v-73193bfd",
    path: "/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73193bfd").then(next)
    },
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-27592132",
    path: "/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27592132").then(next)
    },
  },
  {
    name: "v-48c32d8e",
    path: "/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48c32d8e").then(next)
    },
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-4c0d9326",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c0d9326").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-15753bf4",
    path: "/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15753bf4").then(next)
    },
  },
  {
    name: "v-4ba44278",
    path: "/guide/basic-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ba44278").then(next)
    },
  },
  {
    name: "v-6e550f74",
    path: "/guide/directory-structure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e550f74").then(next)
    },
  },
  {
    name: "v-31ed062c",
    path: "/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31ed062c").then(next)
    },
  },
  {
    name: "v-2d635314",
    path: "/guide/frontmatter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d635314").then(next)
    },
  },
  {
    name: "v-d610c458",
    path: "/guide/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d610c458").then(next)
    },
  },
  {
    name: "v-71c91cf4",
    path: "/guide/global-computed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71c91cf4").then(next)
    },
  },
  {
    name: "v-046112be",
    path: "/guide/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-046112be").then(next)
    },
  },
  {
    name: "v-424f22d8",
    path: "/guide/markdown-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-424f22d8").then(next)
    },
  },
  {
    name: "v-d22237c8",
    path: "/guide/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d22237c8").then(next)
    },
  },
  {
    name: "v-d93efc2c",
    path: "/guide/permalinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d93efc2c").then(next)
    },
  },
  {
    name: "v-8ee52a98",
    path: "/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8ee52a98").then(next)
    },
  },
  {
    name: "v-268e9954",
    path: "/miscellaneous/design-concepts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-268e9954").then(next)
    },
  },
  {
    name: "v-847082bc",
    path: "/miscellaneous/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-847082bc").then(next)
    },
  },
  {
    name: "v-638ea474",
    path: "/miscellaneous/local-development.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-638ea474").then(next)
    },
  },
  {
    name: "v-6577ffdd",
    path: "/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6577ffdd").then(next)
    },
  },
  {
    path: "/plugin/index.html",
    redirect: "/plugin/"
  },
  {
    name: "v-582748f4",
    path: "/miscellaneous/migration-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-582748f4").then(next)
    },
  },
  {
    name: "v-a212054c",
    path: "/plugin/context-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a212054c").then(next)
    },
  },
  {
    name: "v-5616e671",
    path: "/plugin/official/plugin-active-header-links.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5616e671").then(next)
    },
  },
  {
    name: "v-332f7c8e",
    path: "/plugin/life-cycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-332f7c8e").then(next)
    },
  },
  {
    name: "v-79a0aa42",
    path: "/plugin/official/plugin-back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79a0aa42").then(next)
    },
  },
  {
    name: "v-6af103e1",
    path: "/plugin/official/plugin-blog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6af103e1").then(next)
    },
  },
  {
    name: "v-89fb47be",
    path: "/plugin/official/plugin-last-updated.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-89fb47be").then(next)
    },
  },
  {
    name: "v-fa3e623e",
    path: "/plugin/official/plugin-google-analytics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fa3e623e").then(next)
    },
  },
  {
    name: "v-06c4e5db",
    path: "/plugin/official/plugin-medium-zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06c4e5db").then(next)
    },
  },
  {
    name: "v-3a2f823b",
    path: "/plugin/official/plugin-nprogress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a2f823b").then(next)
    },
  },
  {
    name: "v-f7e3059e",
    path: "/plugin/official/plugin-register-components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f7e3059e").then(next)
    },
  },
  {
    name: "v-45f9d9bd",
    path: "/plugin/official/plugin-pwa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45f9d9bd").then(next)
    },
  },
  {
    name: "v-21176a6e",
    path: "/plugin/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21176a6e").then(next)
    },
  },
  {
    name: "v-9bda66be",
    path: "/plugin/official/plugin-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9bda66be").then(next)
    },
  },
  {
    name: "v-285c28ae",
    path: "/plugin/writing-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-285c28ae").then(next)
    },
  },
  {
    name: "v-4ed350ae",
    path: "/plugin/using-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ed350ae").then(next)
    },
  },
  {
    name: "v-862923da",
    path: "/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-862923da").then(next)
    },
  },
  {
    path: "/theme/index.html",
    redirect: "/theme/"
  },
  {
    name: "v-6d3c08d0",
    path: "/theme/blog-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d3c08d0").then(next)
    },
  },
  {
    name: "v-3f66c5b0",
    path: "/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f66c5b0").then(next)
    },
  },
  {
    name: "v-a4987e18",
    path: "/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a4987e18").then(next)
    },
  },
  {
    name: "v-cbb90e60",
    path: "/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cbb90e60").then(next)
    },
  },
  {
    name: "v-6d50c034",
    path: "/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d50c034").then(next)
    },
  },
  {
    name: "v-a36cd298",
    path: "/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a36cd298").then(next)
    },
  },
  {
    name: "v-0cd09506",
    path: "/zh/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cd09506").then(next)
    },
  },
  {
    path: "/zh/index.html",
    redirect: "/zh/"
  },
  {
    name: "v-2a1fb5f3",
    path: "/zh/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a1fb5f3").then(next)
    },
  },
  {
    name: "v-03cd66db",
    path: "/zh/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03cd66db").then(next)
    },
  },
  {
    name: "v-2420937b",
    path: "/zh/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2420937b").then(next)
    },
  },
  {
    name: "v-69e2aa5c",
    path: "/zh/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69e2aa5c").then(next)
    },
  },
  {
    path: "/zh/config/index.html",
    redirect: "/zh/config/"
  },
  {
    name: "v-17596190",
    path: "/zh/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17596190").then(next)
    },
  },
  {
    path: "/zh/faq/index.html",
    redirect: "/zh/faq/"
  },
  {
    name: "v-313265fb",
    path: "/zh/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-313265fb").then(next)
    },
  },
  {
    name: "v-e6099ee0",
    path: "/zh/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e6099ee0").then(next)
    },
  },
  {
    path: "/zh/guide/index.html",
    redirect: "/zh/guide/"
  },
  {
    name: "v-f3e97e0a",
    path: "/zh/guide/basic-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f3e97e0a").then(next)
    },
  },
  {
    name: "v-365252db",
    path: "/zh/guide/frontmatter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-365252db").then(next)
    },
  },
  {
    name: "v-79185249",
    path: "/zh/guide/directory-structure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79185249").then(next)
    },
  },
  {
    name: "v-eca2a082",
    path: "/zh/guide/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eca2a082").then(next)
    },
  },
  {
    name: "v-689355fe",
    path: "/zh/guide/global-computed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-689355fe").then(next)
    },
  },
  {
    name: "v-e4c4834a",
    path: "/zh/guide/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e4c4834a").then(next)
    },
  },
  {
    name: "v-ba7c3c12",
    path: "/zh/guide/markdown-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba7c3c12").then(next)
    },
  },
  {
    name: "v-06ba008a",
    path: "/zh/guide/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06ba008a").then(next)
    },
  },
  {
    name: "v-d4a12896",
    path: "/zh/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d4a12896").then(next)
    },
  },
  {
    name: "v-4987d2ca",
    path: "/zh/miscellaneous/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4987d2ca").then(next)
    },
  },
  {
    name: "v-93257952",
    path: "/zh/miscellaneous/design-concepts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-93257952").then(next)
    },
  },
  {
    name: "v-544f34ce",
    path: "/zh/miscellaneous/local-development.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-544f34ce").then(next)
    },
  },
  {
    name: "v-b9313ede",
    path: "/zh/miscellaneous/migration-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b9313ede").then(next)
    },
  },
  {
    name: "v-2d85d09b",
    path: "/zh/guide/permalinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d85d09b").then(next)
    },
  },
  {
    name: "v-bedc3ca0",
    path: "/zh/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bedc3ca0").then(next)
    },
  },
  {
    path: "/zh/plugin/index.html",
    redirect: "/zh/plugin/"
  },
  {
    name: "v-ddbef3fe",
    path: "/zh/plugin/context-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ddbef3fe").then(next)
    },
  },
  {
    name: "v-7449dba6",
    path: "/zh/plugin/life-cycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7449dba6").then(next)
    },
  },
  {
    name: "v-0fc73524",
    path: "/zh/plugin/official/plugin-active-header-links.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fc73524").then(next)
    },
  },
  {
    name: "v-0c2962d8",
    path: "/zh/plugin/official/plugin-blog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c2962d8").then(next)
    },
  },
  {
    name: "v-5a22024e",
    path: "/zh/plugin/official/plugin-back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a22024e").then(next)
    },
  },
  {
    name: "v-171faad0",
    path: "/zh/plugin/official/plugin-last-updated.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-171faad0").then(next)
    },
  },
  {
    name: "v-25b95174",
    path: "/zh/plugin/official/plugin-google-analytics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25b95174").then(next)
    },
  },
  {
    name: "v-1776f00e",
    path: "/zh/plugin/official/plugin-medium-zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1776f00e").then(next)
    },
  },
  {
    name: "v-ac31c6e4",
    path: "/zh/plugin/official/plugin-nprogress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ac31c6e4").then(next)
    },
  },
  {
    name: "v-fb62cfa4",
    path: "/zh/plugin/official/plugin-pwa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fb62cfa4").then(next)
    },
  },
  {
    name: "v-bae6dd24",
    path: "/zh/plugin/official/plugin-register-components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bae6dd24").then(next)
    },
  },
  {
    name: "v-9c125970",
    path: "/zh/plugin/official/plugin-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9c125970").then(next)
    },
  },
  {
    name: "v-097db593",
    path: "/zh/plugin/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-097db593").then(next)
    },
  },
  {
    name: "v-ef42ccf2",
    path: "/zh/plugin/using-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ef42ccf2").then(next)
    },
  },
  {
    name: "v-6b1c5c12",
    path: "/zh/plugin/writing-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b1c5c12").then(next)
    },
  },
  {
    name: "v-1ebe21b0",
    path: "/zh/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ebe21b0").then(next)
    },
  },
  {
    path: "/zh/theme/index.html",
    redirect: "/zh/theme/"
  },
  {
    name: "v-0a5976bb",
    path: "/zh/theme/blog-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a5976bb").then(next)
    },
  },
  {
    name: "v-fde3950a",
    path: "/zh/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fde3950a").then(next)
    },
  },
  {
    name: "v-33fd437e",
    path: "/zh/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33fd437e").then(next)
    },
  },
  {
    name: "v-6fc5673b",
    path: "/zh/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6fc5673b").then(next)
    },
  },
  {
    name: "v-5f973b26",
    path: "/zh/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f973b26").then(next)
    },
  },
  {
    name: "v-6dcde406",
    path: "/zh/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6dcde406").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]